port: :8000
domain:
debug: true
db_dsn: ./blog.db?_loc=Asia/Shanghai
blog_db_log_file: ./logs/blogdb.log
novel_db_log_file: ./logs/noveldb.log
assets_path: ./templates/static
page_num: 10
portal_html: ./templates/html/portal.html
admin_html: ./templates/html/admin.html
static_path: ./templates/static/

# mysql
mysql_dsn_read: user:password@/dbname?charset=utf8&parseTime=True&loc=Local
mysql_dsn_writ: user:password@/dbname?charset=utf8&parseTime=True&loc=Local
