port: :8000
domain:
debug: true
db_dsn: ./blog.db?_loc=Asia/Shanghai
db_log_file: ./logs/db.log
assets_path: ./templates/static
page_num: 10
portal_html: ./templates/html/portal.html
admin_html: ./templates/html/admin.html
static_path: ./templates/static/
