addr: :80
domain:
db_dsn: ./blog.db?_loc=Asia/Shanghai
log_file: ./blog.log
db_log_file: ./db.log
log_type: true
assets_path: ./templates/static

# 前台模板文件配置
index_html: ./templates/html/index.tmpl
article_html: ./templates/html/article.tmpl
articles_html: ./templates/html/articles.tmpl
categories_html: ./templates/html/categories.tmpl
about_html: ./templates/html/about.tmpl
error_html: ./templates/html/error.tmpl
not_found_html: ./templates/html/not_found.tmpl

# 后台模板文件配置
admin_login_html: ./templates/html/admin_login.tmpl